sudo: false

language: go

# Do not move these lines; they are referred to by README.md.
# Versions of go that are explicitly supported by gonum plus go tip.
go:
 - 1.14.x
 - 1.13.x
 - master

matrix:
 fast_finish: true

before_script:
 # Required for format check.
 - go install golang.org/x/tools/cmd/goimports
 # Required for coverage.
 - go install golang.org/x/tools/cmd/cover
 - go install github.com/mattn/goveralls

go_import_path: gonum.org/v1/tools

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - ${TRAVIS_BUILD_DIR}/.travis/check-formatting.sh
 - go get -d -t -v ./...
 - go build -v ./...
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash ./.travis/test-coverage.sh; fi
 - ${TRAVIS_BUILD_DIR}/.travis/check-imports.sh
 # This is run last since it alters the tree.
 - ${TRAVIS_BUILD_DIR}/.travis/check-generate.sh

